### ISSUE TITLE
Meta version mismatch. // Solution: npm i ngx-select-ex@ng4

### ISSUE THREAD

**Issue by Prasannavk94** [optimistex/ngx-select-ex#6]
Hi,

I am getting meta version mismatch error like found version 4 expected version 3

**Comment by optimistex** [comment]
Hi!
A better solution is to upgrade your project to angular 5.

Or, give me your the "package.joson" from your project. I'll figure out how to ensure compatibility.

**Comment by Prasannavk94** [comment]
Thanks! I will upgrade.

**Comment by RozennK** [comment]
Here is the full text of the error:

ERROR in Error: Metadata version mismatch for module /home/rozennk/projets/projectName/node_modules/ngx-select-ex/ngx-select-ex.d.ts, found version 4, expected 3, resolving symbol FormModule in /home/rozennk/projets/projectName/node_modules/@custom/form/src/form/form.module.d.ts, resolving symbol FormModule in /home/rozennK/projets/projectName/node_modules/@custom/form/src/form/form.module.d.ts
    at syntaxError (/home/rozennk/projets/projectName/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/rozennk/projets/projectName/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/rozennk/projets/projectName/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/rozennk/projets/projectName/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/rozennk/projets/projectName/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/rozennk/projets/projectName/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/rozennk/projets/projectName/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by optimistex** [comment]
I checked the problem. It seems like as Angular 5 differences.

The better solution is to upgrade your project to Angular 5!

If you can't do it then install deprecated version [3.1.2](https://github.com/optimistex/ngx-select-ex/releases/tag/3.1.2):

```console
npm i ngx-select-ex@3.1.2 --save
```

P.S.: [Documentation updated](https://github.com/optimistex/ngx-select-ex#usage).

**Comment by optimistex** [comment]
Ensured support for angular 4.
For usage with Angular 4 install using the following command:
```bush
npm i ngx-select-ex@ng4 --save
```

**Comment by christyfernandes** [comment]
`npm i ngx-select-ex@ng4 --save`

This just saved my day!

**Comment by ChandraTerli** [comment]
I am getting below error with Angular6

ERROR in node_modules/ngx-select-ex/ngx-select/ngx-select.component.d.ts(4,10):
error TS2305: Module '"C:/WBTCollection/Paragon/Main/WebPortal/node_modules/rxjs
/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module '
rxjs-compat/BehaviorSubject'.

**Comment by ChandraTerli** [comment]
more to it...

ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'C:\WBTCollecti
on\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\WBTCollection\Pa
ragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\WBTCollection\Parag
on\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/observable/empty' in 'C:\WBTCol
lection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/observable/from' in 'C:\WBTColl
ection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/observable/of' in 'C:\WBTCollec
tion\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/combineLatest' in 'C:\
WBTCollection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/distinctUntilChanged'
in 'C:\WBTCollection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/do' in 'C:\WBTCollecti
on\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 'C:\WBTColl
ection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'C:\WBTCollect
ion\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/merge' in 'C:\WBTColle
ction\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/mergeMap' in 'C:\WBTCo
llection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/share' in 'C:\WBTColle
ction\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'
ERROR in ./node_modules/ngx-select-ex/esm5/ngx-select-ex.js
Module not found: Error: Can't resolve 'rxjs/add/operator/toArray' in 'C:\WBTCol
lection\Paragon\Main\WebPortal\node_modules\ngx-select-ex\esm5'

**Comment by optimistex** [comment]
@ChandraTerli How did you install it?
`npm i ngx-select-ex` ? Without `@ng4` ?

**Comment by ChandraTerli** [comment]
yes, as mentioned in https://www.npmjs.com/package/ngx-select-ex

**Comment by optimistex** [comment]
@ChandraTerli Okay. I'll try to do something...

**Comment by ChandraTerli** [comment]
thank you!

**Comment by optimistex** [comment]
@ChandraTerli Your issue was moved to the different topic: https://github.com/optimistex/ngx-select-ex/issues/76

**Comment by nikjeni** [comment]
Hi optimistex.. Even i am getting the same error even though i have used with @ng4

0m[0m
[0m[1m[31mERROR in ./src/main.ts[39m[22m[0m
[0m[1m[31mModule not found: Error: Can't resolve './$$_gendir/app/root/root.module.ngfactory' in '/var/lib/jenkins/workspace/dataroomui/src'[39m[22m[0m
[0m[1m[31mERROR in Error: Metadata version mismatch for module /var/lib/jenkins/workspace/dataroomui/node_modules/ngx-select-ex/ngx-select-ex.d.ts, found version 4, expected 3[39m[22m[0m
[0m[1m[31m    at StaticSymbolResolver.getModuleMetadata (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:25586:34)[39m[22m[0m
[0m[1m[31m    at StaticSymbolResolver._createSymbolsOf (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:25374:46)[39m[22m[0m
[0m[1m[31m    at StaticSymbolResolver.getSymbolsOf (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:25355:14)[39m[22m[0m
[0m[1m[31m    at /var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:24214:30[39m[22m[0m
[0m[1m[31m    at Array.forEach (<anonymous>)[39m[22m[0m
[0m[1m[31m    at extractProgramSymbols (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:24213:79)[39m[22m[0m
[0m[1m[31m    at AotCompiler.analyzeModulesAsync (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler/bundles/compiler.umd.js:23771:47)[39m[22m[0m
[0m[1m[31m    at CodeGenerator.codegen (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler-cli/src/codegen.js:32:14)[39m[22m[0m
[0m[1m[31m    at Function.NgTools_InternalApi_NG_2.codeGen (/var/lib/jenkins/workspace/dataroomui/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)[39m[22m[0m
[0m[1m[31m    at _donePromise.Promise.resolve.then (/var/lib/jenkins/workspace/dataroomui/node_modules/@ngtools/webpack/src/plugin.js:428:58)[39m[22m[0m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DataRoom-UI@0.0.0 build-i18n-en: `node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng build --output-path=dataroomui --aot -prod --bh / --i18n-file=src/i18n/messages.en.xlf  --locale=en  --i18n-format=xlf`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DataRoom-UI@0.0.0 build-i18n-en script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by optimistex** [comment]
@nikjeni Hi!
Use the older version: `npm i ngx-select-ex@ng4 --save`
Or upgrade your project to Angular 9

**Comment by nikjeni** [comment]
That's why I am telling you I have used npm i ngx-select-ex@ng4 --save then also same error.
And because of some dependencies, we can't upgrade to 9 versions. please provide me a different solution.
