### ISSUE TITLE
XHR error (404 Not Found) 

### ISSUE THREAD

**Issue by abhisheksaxena741** [optimistex/ngx-select-ex#98]
I am getting below error when using Angular 2.2.0 version and ngx-select version 3.4.0. 
Please help asap. 

> **Error 1:**
GET http://localhost:3000/node_modules/ngx-select-ex/ 404 (Not Found) zone.js:1382 

> **Error 2:**
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ngx-select-ex
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/ngx-select-ex
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/ngx-select-ex as "ngx-select-ex" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/ngx-select-ex as "ngx-select-ex" from http://localhost:3000/app/app.module.js

**Comment by abhisheksaxena741** [comment]
After using `npm i ngx-select-ex@ng4 --save` as well, same issue occurred. However, adding `ngx-selec-ex` node in my systemjs.config.js. Then error went off but a new error is coming as below

> 
![image](https://user-images.githubusercontent.com/39301332/42432704-87139fda-8369-11e8-9f94-e765db5d80bc.png)

**Comment by optimistex** [comment]
@abhisheksaxena741 I see "SystemJs" and I have bad news:
https://github.com/optimistex/ngx-select-ex/issues/26
